# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.srcs/sources_1/ip/clk_mmcm/clk_mmcm.xci
# IP: The module: 'clk_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.gen/sources_1/ip/clk_mmcm/clk_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.gen/sources_1/ip/clk_mmcm/clk_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.gen/sources_1/ip/clk_mmcm/clk_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.srcs/sources_1/ip/clk_mmcm/clk_mmcm.xci
# IP: The module: 'clk_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.gen/sources_1/ip/clk_mmcm/clk_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.gen/sources_1/ip/clk_mmcm/clk_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/505_Project/505_RISC_V/project/work/505_RISC_V_prj.gen/sources_1/ip/clk_mmcm/clk_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
